/**
 * The Map's content: nine Islamic sciences as product-breakdown trees, root to
 * leaf topic. Ported from a standalone reference chart (nine PBS diagrams,
 * built and checked science by science against the classical curricula named
 * in each `frame`), unchanged in substance — this file only holds data, no
 * layout or rendering.
 *
 * `CHARTS`: one entry per science. `config.branches` are its book-level
 * divisions (never أبواب inside one — each chart's own footnote states the
 * rule it follows and what it deliberately leaves out); each branch's `kids`
 * are the topics under it, `[arabic, english]` pairs. `config.footnote` is the
 * chart's own scope note, printed with it.
 *
 * `SUB`: the أبواب inside each kid, drawer-only detail. Keyed
 * "<chartId>.<branchIndex>.<kidIndex>", each value a "·"-separated list.
 */

export const CHARTS = [

/* ---------------------------------------------------------- 06 */
{ id:"06", group:"الآلات · Instrumental", ar:"عُلوم اللُّغة", en:"Arabic Language", frame:"البصريون",
  config:{
  root:{ar:"عُلوم اللُّغة العَرَبِيَّة", en:"Arabic Language Sciences"},
  footnote:[
    "Rule: every level-2 node is a فنّ with its own manual in the البصريون curriculum, never a باب inside one.",
    "So الاشتقاق sits under الصرف, not beside it; التوابع stay inside النحو; البلاغة keeps its fixed order المعاني، البيان، البديع.",
    "النحو governs إعراب, word-endings in context; الصرف governs بنية, word-forms in isolation. No topic drifts between them.",
    "Omitted as أبواب: المبتدأ والخبر، كان وأخواتها، الحال والتمييز، العدد، أوزان الجموع، التشبيه والاستعارة والكناية.",
    "Alternatives: الكوفيون use الخفض والجحد والصرف; الوضع اللغوي is treated in أصول الفقه, not here."
  ],
  branches:[
    {ar:"النَّحو", en:"Syntax & inflection", c:{bar:"#0369a1",fill:"#e0f2fe",text:"#0c4a6e"},
     kids:[["المَرفوعات","Nominatives"],["المَنصوبات","Accusatives"],["المَجرورات","Genitives"],
           ["الجَوازِم والعَوامِل","Jussives & governors"],["التَّوابِع","Appositives"],["الجُمَل وأشباهها","Clauses & phrases"]]},
    {ar:"الصَّرف", en:"Morphology", c:{bar:"#0f766e",fill:"#ccfbf1",text:"#134e4a"},
     kids:[["الميزان الصَّرفي","Morphological measure"],["المُجَرَّد والمَزيد","Bare & augmented"],
           ["الاشتِقاق","Derivation"],["الإعلال والإبدال","Vowel & letter change"],
           ["التَّصغير والنَّسَب","Diminutive & relative"],["التَّثنِية والجَمع","Dual & plural"]]},
    {ar:"البَلاغة", en:"Rhetoric", c:{bar:"#b45309",fill:"#fef3c7",text:"#78350f"},
     kids:[["المَعاني","Sentence semantics"],["البَيان","Imagery & figures"],["البَديع","Embellishment"]]},
    {ar:"اللُّغة والمُعجَم", en:"Lexicography", c:{bar:"#4338ca",fill:"#e0e7ff",text:"#312e81"},
     kids:[["فِقه اللُّغة","Philology"],["المُعجَمات ومَناهِجها","Lexicons & methods"],
           ["الدَّخيل والمُعَرَّب","Loanwords & arabicised"],["المُشتَرَك والأضداد","Homonyms & contronyms"],
           ["الأمثال والنَّوادِر","Proverbs & rarities"]]},
    {ar:"العَروض والقَوافي", en:"Prosody & rhyme", c:{bar:"#be123c",fill:"#ffe4e6",text:"#881337"},
     kids:[["البُحور الشِّعرية","Metres"],["الزِّحافات والعِلَل","Metrical variations"],
           ["القافِية وعُيوبها","Rhyme & its flaws"],["أغراض الشِّعر","Poetic themes"]]},
    {ar:"الإملاء والخَطّ", en:"Orthography & script", c:{bar:"#6d28d9",fill:"#ede9fe",text:"#4c1d95"},
     kids:[["قَواعِد الإملاء","Spelling rules"],["الهَمزة وأحكامها","The hamza"],
           ["عَلامات التَّرقيم","Punctuation"],["أنواع الخُطوط","Scripts & calligraphy"]]}
  ]}},

/* ---------------------------------------------------------- 09 */
{ id:"09", group:"الآلات · Instrumental", ar:"المَنطِق", en:"Logic", frame:"آلة, not a Sharʿī science",
  config:{
  root:{ar:"المَنطِق", en:"Logic"},
  footnote:[
    "Rule: the science bisects exactly; every node falls under التصورات or التصديقات.",
    "المقدمات (حد المنطق، موضوعه، فائدته) are prefatory, not a قسم, so omitted.",
    "الدلالة اللفظية sits in التصورات, where it serves التعريف.",
    "An آلة, not a شرعي science: الغزالي defended it, ابن الصلاح opposed it."
  ],
  branches:[
    {ar:"التَّصَوُّرات", en:"Conceptions", c:{bar:"#0f766e",fill:"#ccfbf1",text:"#134e4a"},
     kids:[["الدَّلالة اللَّفظية","Signification of words"],["الكُلّي والجُزئي","Universal & particular"],
           ["الكُلِّيّات الخَمس","The five predicables"],["النِّسَب الأربع","The four relations"],
           ["الحَدّ والرَّسم","Essential & descriptive definition"],["شُروط التَّعريف","Conditions of definition"]]},
    {ar:"التَّصديقات", en:"Assents", c:{bar:"#4338ca",fill:"#e0e7ff",text:"#312e81"},
     kids:[["القَضايا وأقسامها","Propositions & kinds"],["التَّناقُض","Contradiction"],
           ["العَكس المُستَوي","Simple conversion"],["عَكس النَّقيض","Contraposition"],
           ["القِياس الاقتِراني","Categorical syllogism"],["القِياس الاستِثنائي","Hypothetical syllogism"],
           ["الاستِقراء والتَّمثيل","Induction & analogy"],["الصِّناعات الخَمس","The five arts"],
           ["المُغالَطات","Fallacies"]]}
  ]}},

/* ---------------------------------------------------------- 05 */
{ id:"05", group:"النَّقل · Revelation", ar:"عُلوم القُرآن", en:"Qur'anic Sciences", frame:"السيوطي / الزركشي",
  config:{
  root:{ar:"عُلوم القُرآن", en:"Qur'anic Sciences"},
  footnote:[
    "Rule: every level-2 node is a نوع as الإتقان والبرهان divide it, never a باب inside one.",
    "So الناسخ والمنسوخ sits with دلالات النظم, not النزول, being a property of the ruling; التجويد sits with الأداء beside القراءات, which it is not identical to.",
    "Omitted as أبواب: المتواتر والشاذ من القراءات، الإمالة، المد، أسماء السور، العد الكوفي والبصري.",
    "Excluded as separate sciences: التفسير itself, of which only أصوله appear; أحكام القرآن, which belongs to الفقه وأصوله."
  ],
  branches:[
    {ar:"النُّزول", en:"Revelation & its occasions", c:{bar:"#0f766e",fill:"#ccfbf1",text:"#134e4a"},
     kids:[["كَيفِيّة النُّزول","Modes of revelation"],["أسباب النُّزول","Occasions of revelation"],
           ["المَكّي والمَدَني","Meccan & Medinan"],["أوَّل وآخِر ما نَزَل","First & last revealed"],
           ["أحوال النُّزول","Circumstances of revelation"]]},
    {ar:"الجَمع والرَّسم", en:"Collection & codex", c:{bar:"#b45309",fill:"#fef3c7",text:"#78350f"},
     kids:[["جَمع القُرآن","Collection"],["تَرتيب السُّوَر والآي","Ordering of suras & verses"],
           ["رَسم المُصحَف","Orthography of the codex"],["نَقط المُصحَف وضَبطه","Pointing & vocalisation"],
           ["عَدّ الآي والتَّحزيب","Verse count & divisions"]]},
    {ar:"القِراءات والأداء", en:"Readings & recitation", c:{bar:"#4338ca",fill:"#e0e7ff",text:"#312e81"},
     kids:[["الأحرُف السَّبعة","The seven modes"],["القِراءات المُتواتِرة","Canonical readings"],
           ["الشاذّ من القِراءات","Non-canonical readings"],["الرُّواة والأسانيد","Transmitters & chains"],
           ["التَّجويد وأحكامه","Rules of articulation"],["الوَقف والابتِداء","Pause & resumption"]]},
    {ar:"دَلالات النَّظم", en:"Signification of the text", c:{bar:"#0f172a",fill:"#e2e8f0",text:"#0f172a"},
     kids:[["المُحكَم والمُتشابِه","Clear & ambiguous"],["الناسِخ والمَنسوخ","Abrogating & abrogated"],
           ["العامّ والخاصّ","General & particular"],["المُطلَق والمُقَيَّد","Unrestricted & restricted"],
           ["المُجمَل والمُبَيَّن","Undetailed & clarified"],["غَريب القُرآن والوُجوه","Rare words & polysemy"]]},
    {ar:"الإعجاز والأساليب", en:"Inimitability & style", c:{bar:"#be123c",fill:"#ffe4e6",text:"#881337"},
     kids:[["وُجوه الإعجاز","Aspects of inimitability"],["الأمثال","Parables"],["الأقسام","Oaths"],
           ["القَصَص","Narratives"],["الجَدَل والمُناسَبات","Argument & coherence"],
           ["فَواتِح السُّوَر","Sura openings"]]},
    {ar:"أُصول التَّفسير", en:"Principles of exegesis", c:{bar:"#6d28d9",fill:"#ede9fe",text:"#4c1d95"},
     kids:[["شُروط المُفَسِّر وآدابه","The exegete's conditions"],["التَّفسير بالمأثور","Transmission-based exegesis"],
           ["التَّفسير بالرأي","Reason-based exegesis"],["الإسرائيليات","Israelite reports"],
           ["طَبَقات المُفَسِّرين","Generations of exegetes"]]}
  ]}},

/* ---------------------------------------------------------- 03 */
{ id:"03", group:"النَّقل · Revelation", ar:"عُلوم الحَديث", en:"Hadith Sciences", frame:"ابن الصلاح / ابن حجر",
  config:{
  root:{ar:"عُلوم الحَديث", en:"Hadith Sciences"},
  footnote:[
    "Rule: every level-2 node is a division of مصطلح الحديث in ابن الصلاح وابن حجر, never a باب inside one. The first three branches are three parallel axes of one خبر.",
    "So الجرح والتعديل sits in علوم الإسناد, not beside الصحيح والضعيف, being a science of narrators; الحديث القدسي is classed by its متن, so it sits under القائل.",
    "Omitted as a sub-layer of الضعيف: المرسل، المنقطع، المعضل، المعلق، المدلس، الشاذ، المنكر، المتروك، الموضوع. المشهور والعزيز والغريب divide الآحاد.",
    "الموضوع is taken here as the extreme of الضعيف, not a fourth grade. الحاكم والخطيب list the أنواع as a numbered series rather than by axis."
  ],
  branches:[
    {ar:"باعتِبار الطُّرُق", en:"By number of chains", c:{bar:"#0f766e",fill:"#ccfbf1",text:"#134e4a"},
     kids:[["المُتواتِر","Mass-transmitted"],["الآحاد","Single-chain reports"]]},
    {ar:"باعتِبار القائِل", en:"By whom it is traced to", c:{bar:"#4338ca",fill:"#e0e7ff",text:"#312e81"},
     kids:[["الحَديث القُدسي","Divine saying"],["المَرفوع","Traced to the Prophet"],
           ["المَوقوف","Traced to a Companion"],["المَقطوع","Traced to a Successor"]]},
    {ar:"باعتِبار القَبول", en:"By acceptance & rejection", c:{bar:"#be123c",fill:"#ffe4e6",text:"#881337"},
     kids:[["الصَّحيح","Sound"],["الحَسَن","Fair"],["الضَّعيف","Weak"]]},
    {ar:"عُلوم الإسناد", en:"Sciences of the chain", c:{bar:"#0f172a",fill:"#e2e8f0",text:"#0f172a"},
     kids:[["الجَرح والتَّعديل","Narrator criticism"],["الرِّجال والطَّبَقات","Narrators & generations"],
           ["التَّحَمُّل والأداء","Receiving & transmitting"],["الاتِّصال والانقِطاع","Continuity & breaks"],
           ["العِلَل والشُّذوذ","Hidden defects & anomaly"],["المُتابَعات والشَّواهِد","Corroborations & witnesses"]]},
    {ar:"عُلوم المَتن", en:"Sciences of the text", c:{bar:"#b45309",fill:"#fef3c7",text:"#78350f"},
     kids:[["غَريب الحَديث","Rare wording"],["مُختَلِف الحَديث","Apparently conflicting reports"],
           ["ناسِخ الحَديث ومَنسوخه","Abrogating & abrogated"],["أسباب وُرود الحَديث","Occasions of utterance"],
           ["الرِّواية بالمَعنى","Transmission by meaning"]]},
    {ar:"التَّخريج وكُتُب السُّنَّة", en:"Collections & tracing", c:{bar:"#6d28d9",fill:"#ede9fe",text:"#4c1d95"},
     kids:[["كُتُب السُّنَّة وطَبَقاتها","Collections & their ranks"],["مَناهج المُصَنِّفين","Compilers' methods"],
           ["التَّخريج ودِراسة الأسانيد","Tracing & studying chains"],["الأطراف والزَّوائد","Indexes & additions"],
           ["الألقاب والمُصطَلَحات","Titles & technical terms"]]}
  ]}},

/* ---------------------------------------------------------- 04 */
{ id:"04", group:"الاعتِقاد · Creed", ar:"العَقيدة", en:"Creed", frame:"الماتريدية",
  config:{
  root:{ar:"العَقيدة", en:"Islamic Creed"},
  footnote:[
    "Rule: every level-2 node is a قسم in the Māturīdī manuals (الماتريدي، النسفي، التفتازاني), never a مسألة inside one.",
    "So القدر sits in السمعيات, not under النبوات; الأسماء والصفات sits inside الإلهيات, never parallel to it; مصادر المعرفة opens the chart, as the manuals open.",
    "أفعال العباد والكسب straddles الإلهيات والإيمان; placed under الإلهيات and flagged here.",
    "Omitted as مسائل: صفات المعاني، الاسم والمسمى، خلق القرآن، علامات الساعة، عذاب القبر، الحوض، الميزان.",
    "Alternatives: الأشعرية deny reason access to الحسن والقبح; الأثرية reject the kalām ordering; for الشيعة الإمامة is an أصل of faith."
  ],
  branches:[
    {ar:"مَصادر المَعرِفة", en:"Sources of knowledge", c:{bar:"#475569",fill:"#f1f5f9",text:"#1e293b"},
     kids:[["الحَواسّ السَّليمة","Sound senses"],["الخَبَر الصادِق","Truthful report"],["العَقل","Reason"],
           ["أوَّل الواجِبات","The first obligation"],["الحُسن والقُبح","Reason & moral value"]]},
    {ar:"الإلهِيّات", en:"Theology proper", c:{bar:"#1d4ed8",fill:"#dbeafe",text:"#1e3a8a"},
     kids:[["إثبات الصانِع","Proof of the Creator"],["الذات والوُجوب","Essence & necessity"],
           ["الأسماء والصِّفات","Names & attributes"],["أفعال الله","Divine acts"],
           ["أفعال العِباد والكَسب","Human acts & acquisition"],["الرُّؤية والكَلام","Vision & divine speech"],
           ["التَّوحيد ونَفي الشِّرك","Oneness & negation of shirk"]]},
    {ar:"النُّبُوّات", en:"Prophethood", c:{bar:"#0f766e",fill:"#ccfbf1",text:"#134e4a"},
     kids:[["حَقيقة النُّبُوّة","Nature of prophethood"],["العِصمة","Infallibility"],
           ["المُعجِزة والكَرامة","Miracle & marvel"],["خَتم النُّبُوّة","Finality of prophethood"],
           ["الإسراء والمِعراج","Night journey & ascent"]]},
    {ar:"السَّمعِيّات", en:"Revealed truths", c:{bar:"#b45309",fill:"#fef3c7",text:"#78350f"},
     kids:[["المَلائكة","Angels"],["الكُتُب المُنزَلة","Revealed books"],["القَضاء والقَدَر","Divine decree"],
           ["اليَوم الآخِر","The Last Day"],["البَرزَخ والحِساب","Grave & reckoning"],
           ["الجَنَّة والنار","Paradise & Hell"],["الشَّفاعة","Intercession"],["الجِنّ والغَيب","Jinn & the unseen"]]},
    {ar:"الإيمان ومَسائله", en:"Faith & its questions", c:{bar:"#be123c",fill:"#ffe4e6",text:"#881337"},
     kids:[["حَقيقة الإيمان","Definition of faith"],["زِيادته ونُقصانه","Increase & decrease"],
           ["الاستِثناء في الإيمان","Qualifying one's faith"],["مُرتَكِب الكَبيرة","The grave sinner"],
           ["الكُفر والنِّفاق","Disbelief & hypocrisy"],["التَّكفير وضَوابِطه","Excommunication & its limits"]]},
    {ar:"الإمامة والصَّحابة", en:"Leadership & Companions", c:{bar:"#6d28d9",fill:"#ede9fe",text:"#4c1d95"},
     kids:[["الإمامة وشُروطها","Leadership & conditions"],["الخِلافة الراشِدة","The Rightly-Guided caliphate"],
           ["عَدالة الصَّحابة","Uprightness of Companions"],["التَّفاضُل بينهم","Their relative merit"],
           ["الفِتنة والتَّوَقُّف","The civil strife"]]},
    {ar:"الفِرَق والمِلَل", en:"Sects & religions", c:{bar:"#0f172a",fill:"#e2e8f0",text:"#0f172a"},
     kids:[["أهل السُّنَّة والجَماعة","Sunni orthodoxy"],["فِرَق القِبلة","Sects of the qibla"],
           ["المِلَل والنِّحَل","Other religions & creeds"],["الرَّدّ على المُخالِفين","Refutation of opponents"]]}
  ]}},

/* ---------------------------------------------------------- 02 */
{ id:"02", group:"الشَّريعة · Law", ar:"أُصول الفِقه", en:"Legal Theory", frame:"Hanafi · طريقة الفقهاء",
  config:{
  root:{ar:"أُصول الفِقه", en:"Legal Theory & Methodology"},
  footnote:[
    "Rule: every level-2 node is a قسم in the Hanafi manuals (البزدوي، النسفي، ابن الهمام), never a باب inside one.",
    "So النسخ sits under التعارض, not among الأدلة; الأهلية under الحكم الشرعي, not الاجتهاد; دلالات الألفاظ is raised to a branch, since it governs الكتاب والسنة alike.",
    "Its four children are four parallel classifications of one لفظ: خاص/عام/مشترك/مؤوَّل، ظاهر/نص/مفسَّر/محكم، خفي/مشكل/مجمل/متشابه، عبارة/إشارة/دلالة/اقتضاء.",
    "Omitted as أبواب: أقسام السنة، المرسل، تخصيص العام، الزيادة على النص، العلة ومسالكها. Excluded: القواعد الفقهية, a science of its own; المقاصد, a later systematisation and not a دليل here.",
    "Alternative: طريقة المتكلمين orders it الحكم، الأدلة، الدلالات، الاجتهاد, and rejects الاستحسان وشرع من قبلنا as independent أدلة."
  ],
  branches:[
    {ar:"الأَدِلَّة الأصلِيَّة", en:"Agreed-upon sources", c:{bar:"#0f766e",fill:"#ccfbf1",text:"#134e4a"},
     kids:[["الكِتاب","The Qur'an"],["السُّنَّة","Prophetic Sunna"],["الإجماع","Consensus"],["القِياس","Analogy"]]},
    {ar:"الأَدِلَّة التَّبَعِيَّة", en:"Subsidiary sources", c:{bar:"#b45309",fill:"#fef3c7",text:"#78350f"},
     kids:[["الاستِحسان","Juristic preference"],["العُرف والعادة","Custom & usage"],
           ["قَول الصَّحابي","Companion's verdict"],["شَرع مَن قَبلَنا","Prior revealed law"],
           ["الاستِصحاب","Presumption of continuity"]]},
    {ar:"دَلالات الألفاظ", en:"Signification of expressions", c:{bar:"#4338ca",fill:"#e0e7ff",text:"#312e81"},
     kids:[["عُموم اللَّفظ وخُصوصه","Scope: four classes"],["وُضوح الدَّلالة","Clarity: four degrees"],
           ["خَفاء الدَّلالة","Obscurity: four degrees"],["كَيفِيَّة الدَّلالة","Modes of signification"],
           ["البَيان وأقسامه","Clarification & its kinds"]]},
    {ar:"الحُكم الشَّرعي", en:"The legal ruling", c:{bar:"#0f172a",fill:"#e2e8f0",text:"#0f172a"},
     kids:[["الحُكم التَّكليفي","Obligation-creating rulings"],["الحُكم الوَضعي","Declaratory rulings"],
           ["العَزيمة والرُّخصة","Strict rule & dispensation"],["الحاكِم","The Lawgiver"],
           ["المَحكوم فيه","The act ruled upon"],["المَحكوم عليه","The charged subject"],
           ["الأهلِيَّة وعَوارِضها","Capacity & its impediments"]]},
    {ar:"التَّعارُض والتَّرجيح", en:"Conflict & preponderance", c:{bar:"#be123c",fill:"#ffe4e6",text:"#881337"},
     kids:[["شُروط التَّعارُض","When conflict obtains"],["الجَمع والتَّوفيق","Reconciliation"],
           ["النَّسخ","Abrogation"],["التَّرجيح ووُجوهه","Preponderance & its modes"],
           ["التَّساقُط","Mutual cancellation"]]},
    {ar:"الاجتِهاد والإفتاء", en:"Legal reasoning & fatwa", c:{bar:"#6d28d9",fill:"#ede9fe",text:"#4c1d95"},
     kids:[["الاجتِهاد وشُروطه","Reasoning & its conditions"],["المُجتَهِد والمُفتي","Jurist & mufti"],
           ["التَّقليد والاتِّباع","Following a jurist"],["الفَتوى وآدابها","Issuing fatwa"]]}
  ]}},

/* ---------------------------------------------------------- 01 */
{ id:"01", group:"الشَّريعة · Law", ar:"الفِقه", en:"Jurisprudence", frame:"Hanafi · القدوري",
  config:{
  root:{ar:"الفِقْه", en:"Islamic Jurisprudence"},
  footnote:[
    "Rule: every level-2 node is a كتاب in the Hanafi manuals, never a باب inside one.",
    "So الفرائض والوصايا stand alone, not under المناكحات; الردة والبغي go to السير, not العقوبات; الأضحية is عبادة مالية, not food law; الأيمان والعتاق sit apart from الحظر والإباحة.",
    "Omitted as أبواب: الربا، المهر، الخلع، اللعان، العدة، الاعتكاف، القذف، الجروح, and inside الفرائض: أصحاب الفروض، العصبات، الحجب، العول والرد، ذوو الأرحام.",
    "Excluded as separate sciences: أصول الفقه، القواعد الفقهية، أحاديث الأحكام، علوم القرآن. أحكام العقد likewise belongs to القواعد.",
    "Alternative: الشافعية والشيعة often use a 3-fold split, العبادات / المعاملات / العقوبات."
  ],
  branches:[
    {ar:"العِبادات", en:"Worship · man ↔ Allah", c:{bar:"#0f766e",fill:"#ccfbf1",text:"#134e4a"},
     kids:[["الطَّهارة","Purification"],["الصَّلاة","Prayer"],["الجَنائز","Funeral Rites"],
           ["الزَّكاة","Alms-due"],["الصَّوم","Fasting"],["الحَجّ والعُمرة","Pilgrimage"],
           ["الأُضحِيَّة والعَقيقة","Sacrifice & Newborn Rite"]]},
    {ar:"المُناكَحات", en:"Family Law", c:{bar:"#4338ca",fill:"#e0e7ff",text:"#312e81"},
     kids:[["النِّكاح","Marriage"],["الرَّضاع","Fosterage"],["الطَّلاق","Divorce"],
           ["النَّفَقات","Maintenance"],["الحَضانة والنَّسَب","Custody & Lineage"]]},
    {ar:"المُعامَلات", en:"Civil & Financial Dealings", c:{bar:"#b45309",fill:"#fef3c7",text:"#78350f"},
     kids:[["البُيوع","Sales"],["الصَّرف","Currency Exchange"],["السَّلَم والاستِصناع","Forward & Commissioned Sales"],
           ["الإجارة","Lease & Hire"],["الشَّرِكة","Partnership"],["المُضارَبة","Profit-sharing Venture"],
           ["المُزارَعة والمُساقاة","Crop & Orchard Sharing"],["الوَكالة","Agency"],
           ["الكَفالة والحَوالة","Surety & Debt Transfer"],["الرَّهن","Pledge / Collateral"],
           ["القَرض والدَّين","Loans & Debt"],["الوَديعة والعارِيَّة","Deposit & Loan of Use"],
           ["الهِبة","Gifts"],["الوَقف","Endowment"],["الغَصب والإتلاف","Usurpation & Damage"],
           ["الشُّفعة والقِسمة","Pre-emption & Division"],["اللُّقَطة وإحياء المَوات","Found Property & Land Revival"],
           ["الشِّرب والحيطان","Water Rights & Easements"],["الحَجر والمأذون والإكراه","Interdiction, Licence & Duress"],
           ["اللَّقيط والآبق والمفقود","Foundling, Fugitive & Missing"]]},
    {ar:"الفَرائض والوَصايا", en:"Estates & Bequests", c:{bar:"#0f172a",fill:"#e2e8f0",text:"#0f172a"},
     kids:[["تَجهيز التَّرِكة والدُّيون","Estate Settlement & Debts"],["الوَصايا","Bequests & Wills"],
           ["الفَرائض","Division of Inheritance"]]},
    {ar:"الجِنايات والعُقوبات", en:"Crimes & Punishments", c:{bar:"#be123c",fill:"#ffe4e6",text:"#881337"},
     kids:[["الحُدود","Fixed Penalties"],["السَّرِقة وقَطع الطَّريق","Theft & Brigandage"],
           ["الجِنايات والقِصاص","Bodily Harm & Retaliation"],["الدِّيات والمَعاقِل","Blood Money & Liability"],
           ["التَّعزير","Discretionary Penalties"]]},
    {ar:"القَضاء والشَّهادات والسِّيَر", en:"Judiciary & International", c:{bar:"#6d28d9",fill:"#ede9fe",text:"#4c1d95"},
     kids:[["أدب القاضي","Judgeship"],["الشَّهادات","Testimony"],["الدَّعاوى والبَيِّنات","Claims & Evidence"],
           ["الإقرار","Admission"],["الصُّلح","Settlement"],["السِّيَر والجِهاد","Intl. Relations & Warfare"],
           ["الجِزية وأهل الذِّمَّة","Non-Muslim Subjects"],["الرِّدَّة والبَغي","Apostasy & Rebellion"]]},
    {ar:"الأَيمان والعَتاق", en:"Oaths, Expiations & Manumission", c:{bar:"#047857",fill:"#d1fae5",text:"#064e3b"},
     kids:[["الأَيمان","Oaths"],["النُّذور","Vows"],["الكَفّارات","Expiations"],
           ["العَتاق","Manumission"],["المُكاتَب","Contracted Manumission"],["الوَلاء","Clientage"]]},
    {ar:"الحَظر والإباحة", en:"The Forbidden & the Permitted", c:{bar:"#0369a1",fill:"#e0f2fe",text:"#0c4a6e"},
     kids:[["الذَّبائح","Ritual Slaughter"],["الصَّيد","Hunting"],["الأطعِمة والأشرِبة","Food & Drink"],
           ["اللِّباس والزِّينة","Dress & Adornment"],["الكَراهِيَة والآداب","Disliked Acts & Etiquette"]]}
  ]}},

/* ---------------------------------------------------------- 07 */
{ id:"07", group:"الشَّريعة · Law", ar:"القَواعِد الفِقهِيّة", en:"Legal Maxims", frame:"Hanafi · ابن نجيم / المجلة",
  config:{
  root:{ar:"القَواعِد الفِقهِيَّة", en:"Legal Maxims"},
  footnote:[
    "Rule: the five قواعد كبرى are the branches, since the maxims under each are derived from it, not merely related to it.",
    "Tier discipline: a قاعدة is general; a ضابط is chapter- and madhhab-specific. They never share a level, so الضوابط form their own branch with الفروق والنظائر.",
    "About الفقه but not part of it, so the الفروع cited as illustrations are omitted: بيع الوفاء، خيار الرؤية، ضمان المغصوب.",
    "المجلة fixes 99 articles in this order. السيوطي وابن السبكي count four كبرى, folding لا ضرر into المشقة تجلب التيسير."
  ],
  branches:[
    {ar:"الأُمور بمَقاصِدها", en:"Acts follow intent", c:{bar:"#0f766e",fill:"#ccfbf1",text:"#134e4a"},
     kids:[["لا ثَواب إلا بالنِّيّة","Intent conditions reward"],["العِبرة بالمَقاصِد","Intent over wording"],
           ["مَن تَعَجَّل حُرِم","Hastening forfeits the right"],["اليَمين على نِيّة الحالِف","Oaths follow intent"]]},
    {ar:"اليَقين لا يَزول بالشَّكّ", en:"Certainty is not lifted by doubt", c:{bar:"#4338ca",fill:"#e0e7ff",text:"#312e81"},
     kids:[["الأصل بَقاء ما كان","Presumption of continuity"],["الأصل بَراءة الذِّمّة","Presumption of non-liability"],
           ["الأصل في الأشياء الإباحة","Presumption of permissibility"],["لا دَلالة مع التَّصريح","Explicit overrides implicit"],
           ["الحادِث يُضاف لأقرَب وَقت","Recent-cause presumption"]]},
    {ar:"المَشَقّة تَجلِب التَّيسير", en:"Hardship brings facility", c:{bar:"#b45309",fill:"#fef3c7",text:"#78350f"},
     kids:[["الضَّرورات تُبيح المَحظورات","Necessity permits the forbidden"],["الضَّرورة تُقَدَّر بقَدَرها","Necessity is measured"],
           ["الحاجة كالضَّرورة","Need can stand for necessity"],["ما جاز لعُذر بَطَل بزَواله","Excuse ends with its cause"],
           ["إذا ضاق الأمر اتَّسَع","Hardship widens the scope"]]},
    {ar:"لا ضَرَر ولا ضِرار", en:"No harm & no reciprocal harm", c:{bar:"#be123c",fill:"#ffe4e6",text:"#881337"},
     kids:[["الضَّرَر يُزال","Harm is removed"],["الضَّرَر لا يُزال بمِثله","Not removed by like harm"],
           ["الأشَدّ يُزال بالأخَفّ","Greater harm by lesser"],["تَحَمُّل الضَّرَر الخاصّ","Private harm for public good"],
           ["دَرء المَفاسِد مُقَدَّم","Averting harm takes priority"]]},
    {ar:"العادة مُحَكَّمة", en:"Custom is arbitral", c:{bar:"#6d28d9",fill:"#ede9fe",text:"#4c1d95"},
     kids:[["استِعمال الناس حُجّة","Common usage is authority"],["المَعروف كالمَشروط","Custom equals stipulation"],
           ["التَّعيين بالعُرف كالنَّصّ","Custom specifies like text"],["اعتِبار العادة باطِّرادها","Custom must be consistent"],
           ["تَغَيُّر الأحكام بالزَّمان","Rulings change with times"]]},
    {ar:"الضَّوابِط والنَّظائر", en:"Chapter-rules & parallels", c:{bar:"#0f172a",fill:"#e2e8f0",text:"#0f172a"},
     kids:[["القاعِدة والضابِط","Maxim vs chapter-rule"],["الضَّوابِط المَذهَبية","Madhhab-specific rules"],
           ["الفُروق","Distinctions"],["الأشباه والنَّظائر","Parallels & likenesses"],
           ["الاستِثناءات","Exceptions to the maxims"]]}
  ]}},

/* ---------------------------------------------------------- 08 */
{ id:"08", group:"السُّلوك · The Path", ar:"التَّزكية", en:"Purification of the Soul", frame:"الغزالي · الإحياء",
  config:{
  root:{ar:"التَّزكِية", en:"Purification of the Soul"},
  footnote:[
    "Rule: the branches follow the أرباع of الإحياء with the path's own divisions beside them; no node is a فصل lifted from a كتاب.",
    "Tier discipline: a مقام is earned and stable, a حال is bestowed and passing, so القبض والبسط والفناء are not listed among المقامات.",
    "Omitted as فصول: رياضة النفس، كسر الشهوتين، ذم الجاه، ذم البخل، آفات الغيبة.",
    "Frame: تصوف as a سلوك path, not أخلاق as virtue ethics (مسكويه، الراغب). Later Naqshbandī manuals reorder around الذكر والمراقبة والرابطة."
  ],
  branches:[
    {ar:"آداب العِبادات والعادات", en:"Inward etiquette", c:{bar:"#0f766e",fill:"#ccfbf1",text:"#134e4a"},
     kids:[["أسرار العِبادات","Inner meanings of worship"],["آداب تِلاوة القُرآن","Etiquette of recitation"],
           ["آداب الدُّعاء والذِّكر","Etiquette of supplication"],["آداب المَعيشة والكَسب","Livelihood & earning"]]},
    {ar:"المُهلِكات", en:"Destructive vices", c:{bar:"#be123c",fill:"#ffe4e6",text:"#881337"},
     kids:[["الكِبر والعُجب","Arrogance & vanity"],["الحَسَد","Envy"],["الرِّياء","Ostentation"],
           ["الغَضَب والحِقد","Anger & rancour"],["حُبّ الدُّنيا والمال","Love of world & wealth"],
           ["آفات اللِّسان","Vices of the tongue"],["شَهوة البَطن والفَرج","Appetites of belly & loins"]]},
    {ar:"المُنجِيات", en:"Saving virtues", c:{bar:"#0f172a",fill:"#e2e8f0",text:"#0f172a"},
     kids:[["التَّوبة","Repentance"],["الصَّبر والشُّكر","Patience & gratitude"],["الخَوف والرَّجاء","Fear & hope"],
           ["الزُّهد والفَقر","Renunciation & poverty"],["التَّوَكُّل","Reliance on God"],
           ["الإخلاص والصِّدق","Sincerity & truthfulness"],["المَحَبّة والرِّضا","Love & contentment"],
           ["ذِكر المَوت","Remembrance of death"]]},
    {ar:"المَقامات والأحوال", en:"Stations & states", c:{bar:"#4338ca",fill:"#e0e7ff",text:"#312e81"},
     kids:[["المَقامات المُكتَسَبة","Earned stations"],["الأحوال المَوهوبة","Bestowed states"],
           ["الفَرق بينهما","The distinction between them"],["المُجاهَدة والرِّياضة","Struggle & discipline"],
           ["الكَشف والإلهام","Unveiling & inspiration"]]},
    {ar:"الذِّكر والمُراقَبة", en:"Remembrance & vigilance", c:{bar:"#b45309",fill:"#fef3c7",text:"#78350f"},
     kids:[["الذِّكر وآدابه","Remembrance & its etiquette"],["الأوراد والوَظائف","Daily litanies"],
           ["المُحاسَبة والمُراقَبة","Self-reckoning & watchfulness"],["التَّفَكُّر","Contemplation"]]},
    {ar:"آداب السُّلوك والصُّحبة", en:"Conduct & companionship", c:{bar:"#6d28d9",fill:"#ede9fe",text:"#4c1d95"},
     kids:[["الشَّيخ والمُريد","Master & aspirant"],["آداب الصُّحبة","Etiquette of companionship"],
           ["العُزلة والخَلوة","Seclusion & retreat"],["الأمر بالمَعروف","Enjoining the good"],
           ["آداب السَّفَر والسَّماع","Travel & audition"]]}
  ]}}

]

export const SUB = {
/* ---- 06 اللغة ---- */
"06.0.0":"الفاعل · نائب الفاعل · المبتدأ والخبر · اسم كان وخبر إنّ",
"06.0.1":"المفاعيل الخمسة · الحال · التمييز · الاستثناء · خبر كان واسم إنّ",
"06.0.2":"حروف الجرّ ومعانيها · المضاف والمضاف إليه · الإضافة اللفظية والمعنوية · شبه الجملة",
"06.0.3":"جزم المضارع · أدوات الشرط · نصب المضارع · العامل والمعمول · الإعراب والبناء",
"06.0.4":"النعت · العطف · التوكيد · البدل · عطف البيان",
"06.0.5":"الاسمية والفعلية · الجمل التي لها محلّ · الشرطية · الاعتراضية والصلة",
"06.1.0":"الفاء والعين واللام · الزيادة والحذف · وزن الرباعي والخماسي",
"06.1.1":"أوزان الثلاثي المجرد · مزيد الثلاثي · الرباعي ومزيده · معاني الزيادة",
"06.1.2":"اسم الفاعل والمفعول · الصفة المشبهة · صيغ المبالغة · اسم التفضيل · اسما الزمان والمكان · المصدر",
"06.1.3":"الإعلال بالقلب والحذف والتسكين · الإبدال · الإدغام · أحكام الوقف",
"06.1.4":"أوزان التصغير · تصغير الترخيم · ياء النسب · النسب الشاذّ",
"06.1.5":"المثنّى وملحقاته · جمع المذكر السالم · جمع المؤنث السالم · جموع التكسير وأوزانها",
"06.2.0":"الخبر والإنشاء · المسند والمسند إليه · القصر · الفصل والوصل · الإيجاز والإطناب",
"06.2.1":"التشبيه · الحقيقة والمجاز · الاستعارة · الكناية",
"06.2.2":"الجناس والسجع · الطباق والمقابلة · التورية · حسن التعليل · براعة الاستهلال",
"06.3.0":"نشأة اللغة · اللهجات العربية · التطور الدلالي · الفصحى والعامية",
"06.3.1":"ترتيب المخارج · ترتيب القافية · الترتيب الألفبائي · أشهر المعاجم",
"06.3.2":"ضوابط التعريب · المولَّد · الدخيل المحدث",
"06.3.3":"الترادف · المشترك اللفظي · الأضداد · إنكارها عند بعضهم",
"06.3.4":"كتب الأمثال · النوادر · الحِكَم · مورد المثل ومضربه",
"06.4.0":"التفعيلات · دوائر الخليل · البحور الستة عشر · المجزوء والمشطور",
"06.4.1":"الزحاف المفرد والمزدوج · علل الزيادة · علل النقص · الخرم والخبن",
"06.4.2":"حروف القافية · حركاتها · أنواع القافية · الإقواء والإكفاء والسناد",
"06.4.3":"المدح · الهجاء · الرثاء · الوصف · الغزل والحماسة",
"06.5.0":"الألف اللينة · التاء المربوطة والمفتوحة · الحذف والزيادة · الوصل والفصل",
"06.5.1":"همزة الوصل والقطع · المتوسطة · المتطرفة · الممدودة",
"06.5.2":"الفاصلة والنقطة · الاستفهام والتعجب · النقطتان والشرطة · الأقواس",
"06.5.3":"الكوفي · النسخ · الثلث · الرقعة · الديواني والفارسي",
/* ---- 09 المنطق ---- */
"09.0.0":"المطابقة · التضمّن · الالتزام · المفرد والمركّب",
"09.0.1":"الكلي الطبيعي والمنطقي والعقلي · الجزئي الحقيقي والإضافي · المتواطئ والمشكّك",
"09.0.2":"الجنس · النوع · الفصل · الخاصّة · العرض العامّ",
"09.0.3":"التساوي · التباين · العموم المطلق · العموم من وجه",
"09.0.4":"التامّ والناقص · الحدّ بالجنس والفصل · الرسم بالخاصّة",
"09.0.5":"الجامع المانع · الدور والتسلسل · الأخفى والمساوي · الألفاظ الغريبة",
"09.1.0":"الحملية والشرطية · الموجبة والسالبة · الكلية والجزئية والشخصية · المهملة · الموجّهات",
"09.1.1":"شروط التناقض الثمانية · تناقض المحصورات · تناقض الشرطيات",
"09.1.2":"عكس الكلية الموجبة · عكس السالبة · ما لا ينعكس · شروطه",
"09.1.3":"الموافق والمخالف · شروطه · فرقه عن المستوي",
"09.1.4":"الحدود الثلاثة · الأشكال الأربعة · شروط الإنتاج · الضروب المنتجة",
"09.1.5":"المتصل · المنفصل · وضع المقدَّم ورفع التالي · شروط الإنتاج",
"09.1.6":"التامّ والناقص · حجية الاستقراء · التمثيل والقياس الفقهي",
"09.1.7":"البرهان · الجدل · الخطابة · الشعر · السفسطة",
"09.1.8":"المادية واللفظية · المصادرة على المطلوب · الدور · مغالطة الاشتراك",
/* ---- 05 علوم القرآن ---- */
"05.0.0":"التنزيل الجملي والمنجَّم · حكمة التنجيم · أنواع الوحي · كيفية تلقّيه",
"05.0.1":"صيغ سبب النزول · العبرة بعموم اللفظ · تعدد النازل والسبب · كتب الأسباب",
"05.0.2":"ضوابط التمييز · خصائص كلٍّ منهما · فائدة معرفته · ما نزل بمكة وحكمه مدني",
"05.0.3":"أول ما نزل مطلقًا · آخر ما نزل · أوائل الموضوعات",
"05.0.4":"الليلي والنهاري · السفري والحضري · الصيفي والشتائي · ما نزل مرتين",
"05.1.0":"في عهد النبي · جمع أبي بكر · جمع عثمان · حرق المصاحف",
"05.1.1":"توقيفية الآي · ترتيب السور والاجتهاد · مصاحف الصحابة",
"05.1.2":"الرسم العثماني · قواعده الست · الحذف والزيادة · حكم الالتزام به",
"05.1.3":"نقط الإعجام · نقط الإعراب · أبو الأسود والخليل · علامات الوقف",
"05.1.4":"المدني والمكي والكوفي والبصري · أسباب الاختلاف · الأجزاء والأحزاب · التخميس والتعشير",
"05.2.0":"معناها · أقوال العلماء فيها · علاقتها بالقراءات · حكمة التيسير",
"05.2.1":"القراء السبعة · الثلاثة المتمّمة · شروط القراءة الصحيحة · الطرق والروايات",
"05.2.2":"ضابط الشذوذ · القراءات الأربع · الاحتجاج بها فقهًا ولغةً · التفسير بها",
"05.2.3":"الرواة عن كل قارئ · الأسانيد المتصلة · الإجازة والسند · طبقات القراء",
"05.2.4":"مخارج الحروف · الصفات · أحكام النون والميم · المدود · الإمالة والتفخيم",
"05.2.5":"التامّ والكافي والحسن · الوقف القبيح · السكت والقطع · علاماته",
"05.3.0":"تعريفهما · الحروف المقطَّعة · الراسخون في العلم · التأويل والتفويض",
"05.3.1":"أنواع النسخ · نسخ التلاوة والحكم · شروطه · المنسوخات المذكورة",
"05.3.2":"صيغ العموم · المخصِّصات المتصلة والمنفصلة · العام المراد به الخصوص",
"05.3.3":"حمل المطلق على المقيَّد · اتحاد الحكم والسبب · أمثلته",
"05.3.4":"أسباب الإجمال · المبيَّن بالسنة · تأخير البيان",
"05.3.5":"مفردات الغريب · الوجوه والنظائر · المعرَّب في القرآن · كتب الغريب",
"05.4.0":"البلاغي · الغيبي · العلمي · التشريعي · الصرفة وردّها",
"05.4.1":"المصرَّحة والكامنة · فوائدها · أمثلتها القرآنية",
"05.4.2":"المقسَم به والمقسَم عليه · حكمة القسم · حذف أداة القسم",
"05.4.3":"أنواعه · تكراره وحكمته · فوائده · الفرق عن الأساطير",
"05.4.4":"أساليب الحِجاج · مناسبة الآيات · مناسبة السور · فواصل الآي",
"05.4.5":"أنواعها العشرة · الحروف المقطَّعة · الافتتاح بالحمد والنداء",
"05.5.0":"العلوم المطلوبة · صحة المعتقد · التجرّد عن الهوى · آدابه في الترجيح",
"05.5.1":"القرآن بالقرآن · بالسنة · بأقوال الصحابة · بالتابعين · أشهر كتبه",
"05.5.2":"المحمود والمذموم · شروط جوازه · التفسير الإشاري · الاتجاهات الحديثة",
"05.5.3":"أقسامها · موقف العلماء منها · مصادرها · أثرها في كتب التفسير",
"05.5.4":"مفسرو الصحابة · التابعون · مدارس مكة والمدينة والعراق · طبقات المتأخرين",
/* ---- 03 الحديث ---- */
"03.0.0":"شروطه · اللفظي والمعنوي · إفادته العلم اليقيني · قلة أمثلته",
"03.0.1":"المشهور · العزيز · الغريب · إفادته الظنّ · حجيته في العمل",
"03.1.0":"نسبته لفظًا ومعنًى · الفرق عن القرآن · عدده وأمثلته",
"03.1.1":"القولي والفعلي والتقريري · الصفات الخَلقية والخُلقية · المرفوع حكمًا",
"03.1.2":"قول الصحابي وفعله · حكمه · ما له حكم الرفع",
"03.1.3":"قول التابعي · الفرق عن المنقطع · الاحتجاج به",
"03.2.0":"لذاته ولغيره · شروطه الخمسة · أصحّ الأسانيد · مراتبه",
"03.2.1":"لذاته ولغيره · خفّة الضبط · الاحتجاج به · اصطلاح الترمذي",
"03.2.2":"المرسل والمنقطع والمعضل · المعلّق والمدلَّس · الشاذّ والمنكر · المتروك والموضوع · العمل به في الفضائل",
"03.3.0":"ألفاظ الجرح · ألفاظ التعديل · تعارضهما · الجرح المبهم · كتب الرجال",
"03.3.1":"الصحابة والتابعون · الطبقات · الكنى والأنساب · المؤتلف والمختلف · تواريخ الوفيات",
"03.3.2":"السماع والعرض · الإجازة والمناولة · المكاتبة والوجادة · صيغ الأداء",
"03.3.3":"المسند والمتصل · المعنعن والمؤنَّن · اللقاء والمعاصرة · المزيد في متصل الأسانيد",
"03.3.4":"الحديث المعلّ · القلب والإدراج · الاضطراب والتصحيف · المخالفة للأوثق",
"03.3.5":"الاعتبار · المتابعة التامة والقاصرة · الشاهد · تقوية الضعيف",
"03.4.0":"كتبه المصنَّفة · شرح الألفاظ · الرجوع إلى اللغة",
"03.4.1":"الجمع · الترجيح · النسخ · التوقّف",
"03.4.2":"طرق معرفة النسخ · أمثلته · الفرق عن التخصيص",
"03.4.3":"أنواع الأسباب · أثرها في الفهم · كتبها",
"03.4.4":"شروط جوازها · خلاف العلماء فيها · أثرها في الألفاظ",
"03.5.0":"الصحيحان · السنن · المسانيد · المعاجم والمستدركات · الأجزاء",
"03.5.1":"شرط البخاري ومسلم · التبويب · التعليقات · الاستنباط من الترجمة",
"03.5.2":"طرق التخريج الخمس · جمع الطرق · الحكم على الإسناد",
"03.5.3":"كتب الأطراف · كتب الزوائد · مجمع الزوائد · فائدتها",
"03.5.4":"أمير المؤمنين في الحديث · الحافظ والحجة · المدبَّج والأقران · رواية الأكابر عن الأصاغر",
/* ---- 04 العقيدة ---- */
"04.0.0":"الحواس الخمس · شروط صحتها · مواضع خطأ الحسّ",
"04.0.1":"خبر المتواتر · خبر الرسول · إفادته اليقين",
"04.0.2":"البديهي والنظري · حدوده · تقدّمه في إثبات الصانع",
"04.0.3":"النظر أم المعرفة · حكم تارك النظر · الإيمان التقليدي",
"04.0.4":"العقلي والشرعي · موقف الماتريدية · خلاف الأشاعرة والمعتزلة",
"04.1.0":"دليل الحدوث · دليل الإمكان · دليل العناية",
"04.1.1":"الوجود الواجب · القِدم والبقاء · المخالفة للحوادث · القيام بالنفس · الوحدانية",
"04.1.2":"صفات الذات · صفات الفعل · التكوين عند الماتريدية · المتشابهات والتأويل · الاسم والمسمّى",
"04.1.3":"الحكمة والتعليل · خلق الشرّ · وجوب الأصلح · اللطف",
"04.1.4":"الجبر والاختيار · الكسب · الاستطاعة · التوفيق والخذلان",
"04.1.5":"الرؤية في الآخرة · بلا كيف ولا جهة · الكلام النفسي · خلق القرآن",
"04.1.6":"أقسام التوحيد · الشرك الأكبر والأصغر · التوسل والوسائل",
"04.2.0":"النبي والرسول · الحاجة إلى البعثة · الاصطفاء",
"04.2.1":"العصمة في التبليغ · قبل النبوة وبعدها · الصغائر والسهو",
"04.2.2":"شروط المعجزة · الفرق عن السحر · كرامة الوليّ · الإرهاص",
"04.2.3":"دليله من الكتاب والسنة · دعوى النبوة بعده · نزول عيسى",
"04.2.4":"بالروح والجسد · دليله · ما رآه النبي",
"04.3.0":"خلقهم وطبيعتهم · وظائفهم · عصمتهم · فضلهم على البشر",
"04.3.1":"الكتب الأربعة · الصحف · التحريف · هيمنة القرآن",
"04.3.2":"مراتب القدر الأربع · الهداية والضلال · الأجل والرزق · الاحتجاج بالقدر",
"04.3.3":"أشراط الساعة · النفخ في الصور · البعث والنشور · الصراط",
"04.3.4":"فتنة القبر · عذابه ونعيمه · الحساب والعرض · الميزان · تطاير الصحف",
"04.3.5":"وجودهما الآن · أبديتهما · نعيم الجنة · خروج الموحدين · الحوض والكوثر",
"04.3.6":"أنواعها · شفاعة النبي · شفاعة غيره · منكروها",
"04.3.7":"خلق الجنّ · تكليفهم · السحر والعين · اختصاص الله بعلم الغيب",
"04.4.0":"التصديق والإقرار · دخول العمل فيه · خلاف الماتريدية والأشاعرة",
"04.4.1":"ثبات التصديق · زيادة الأعمال · خلاف أهل السنة فيه",
"04.4.2":"معناه · منع الحنفية له · وجه المجيزين",
"04.4.3":"لا يُكفَّر · تحت المشيئة · ردّ الخوارج والمعتزلة · المنزلة بين المنزلتين",
"04.4.4":"كفر الجحود والإنكار · النفاق الاعتقادي والعملي · أحكام المنافقين",
"04.4.5":"شروطه وموانعه · التأويل والجهل والإكراه · لازم القول · خطر التسرّع",
"04.5.0":"وجوب نصب الإمام · شرط القرشية · طرق الانعقاد · طاعة الإمام الجائر",
"04.5.1":"ترتيب الخلفاء · مدتها · حديث الخلافة ثلاثون",
"04.5.2":"تعريف الصحابي · تعديلهم جملةً · قبول روايتهم",
"04.5.3":"أفضلية الشيخين · العشرة المبشَّرون · أهل البيت",
"04.5.4":"الإمساك عمّا شجر بينهم · التأويل والاجتهاد · نقد الروايات التاريخية",
"04.6.0":"الماتريدية · الأشعرية · أهل الحديث · أصول اتفاقهم",
"04.6.1":"الخوارج · المعتزلة · الشيعة · المرجئة · الجهمية والمجسِّمة",
"04.6.2":"اليهودية والنصرانية · المجوس والصابئة · الفلاسفة · الدهرية",
"04.6.3":"مناهج الردّ · أدب المناظرة · التكفير والتبديع · كتب المقالات",
/* ---- 02 أصول الفقه ---- */
"02.0.0":"تعريفه وتواتره · حجيته · القراءات الشاذة والاستدلال بها",
"02.0.1":"المتواتر والمشهور والآحاد · المرسل · الفعل والتقرير · شرط الرواة عند الحنفية",
"02.0.2":"أركانه · الإجماع السكوتي · إجماع أهل المدينة · انقراض العصر",
"02.0.3":"الأصل والفرع · العلة ومسالكها · شروط الحكم · القوادح · التخريج والتنقيح",
"02.1.0":"أنواعه · استحسان النص والإجماع · الضرورة والعرف · إنكار الشافعي له",
"02.1.1":"العامّ والخاصّ · القولي والعملي · شروط اعتباره · تغيره بالزمان",
"02.1.2":"فيما لا مجال للرأي فيه · عند اختلافهم · تقديمه على القياس",
"02.1.3":"ما ورد في شرعنا · ما نُسخ منه · حجيته عند الحنفية",
"02.1.4":"أنواعه · الاستصحاب المقلوب · حجيته في الدفع لا الإثبات · مسألة المفقود",
"02.2.0":"الخاصّ · العامّ · المشترك · المؤوَّل",
"02.2.1":"الظاهر · النصّ · المفسَّر · المحكم",
"02.2.2":"الخفي · المشكل · المجمل · المتشابه",
"02.2.3":"عبارة النصّ · إشارة النصّ · دلالة النصّ · اقتضاء النصّ · إنكار مفهوم المخالفة",
"02.2.4":"بيان التقرير والتفسير · بيان التغيير والتبديل · بيان الضرورة · تأخير البيان",
"02.3.0":"الفرض والواجب · السنة والمندوب · المباح · الحرام والمكروهان",
"02.3.1":"السبب · الشرط · المانع · الصحة والفساد والبطلان",
"02.3.2":"أقسام الرخصة · رخصة الترفيه · رخصة الإسقاط · حكم الأخذ بها",
"02.3.3":"الحاكم هو الله · حكم العقل قبل البعثة · التحسين والتقبيح",
"02.3.4":"شروط الفعل المكلَّف به · القدرة والاستطاعة · حق الله وحق العبد",
"02.3.5":"شروط التكليف · الفهم والقدرة · تكليف الغافل والصبي",
"02.3.6":"أهلية الوجوب · أهلية الأداء · العوارض السماوية · العوارض المكتسبة · الذمة",
"02.4.0":"اتحاد المحلّ والوقت · تساوي القوة · امتناعه بين قطعي وظني",
"02.4.1":"حمل العام على الخاص · المطلق على المقيَّد · بيان اختلاف المحلّ",
"02.4.2":"شروطه · نسخ الكتاب بالسنة · نسخ التلاوة والحكم · الزيادة على النص",
"02.4.3":"الترجيح بالسند · بالمتن · بالمدلول · بأمر خارج",
"02.4.4":"الرجوع إلى ما دونهما · الرجوع إلى الأصل · تعذّر العمل بهما",
"02.5.0":"شروط المجتهد · تجزّؤ الاجتهاد · التصويب والتخطئة · اجتهاد النبي",
"02.5.1":"طبقات الفقهاء · المطلق والمقيَّد · المفتي غير المجتهد",
"02.5.2":"حكم التقليد · تقليد العامي · تتبّع الرخص · الانتقال بين المذاهب",
"02.5.3":"شروط المفتي · صيغ الفتوى · آداب المستفتي · تغيّر الفتوى",
/* ---- 01 الفقه ---- */
"01.0.0":"المياه · الوضوء والغسل · التيمم · المسح على الخفين · النجاسات · الحيض والنفاس",
"01.0.1":"الأوقات والأذان · الشروط والأركان · الواجبات والسنن · الإمامة والجماعة · الجمعة والعيدان · صلاة السفر والمريض · سجود السهو · الوتر والنوافل",
"01.0.2":"الغسل والتكفين · الصلاة على الميت · الدفن والتعزية · الشهيد · إسقاط السقط",
"01.0.3":"النصاب والحول · زكاة السائمة · زكاة النقدين وعروض التجارة · العشر والخراج · المصارف الثمانية · صدقة الفطر",
"01.0.4":"رؤية الهلال · النية · المفسدات · القضاء والكفارة · الفدية · الاعتكاف",
"01.0.5":"المواقيت والإحرام · الطواف والسعي · الوقوف بعرفة والمزدلفة · الهدي والحلق · جنايات الإحرام · الفوات والإحصار",
"01.0.6":"وقت الذبح · شروط الأضحية · القسمة والادّخار · العقيقة · النذر بالأضحية",
"01.1.0":"الخطبة · الأركان والشهود · الوليّ والكفاءة · المحرَّمات · المهر · النكاح الفاسد",
"01.1.1":"مدة الرضاع · المقدار المحرِّم · الشهادة عليه · أثره في التحريم",
"01.1.2":"الصريح والكناية · السني والبدعي · الرجعي والبائن · الخلع · الإيلاء والظهار · اللعان · العدة والرجعة",
"01.1.3":"نفقة الزوجة · نفقة الأولاد · نفقة الأقارب · السكنى · حال الإعسار",
"01.1.4":"مدة الحضانة · أحقّ الناس بها · ثبوت النسب · الإقرار بالنسب · القافة",
"01.2.0":"الانعقاد والقبض · الخيارات · الربا · الفاسد والباطل · المرابحة والتولية · الإقالة",
"01.2.1":"التقابض في المجلس · بيع النقد بالنقد · التفاضل · الشركة في الصرف",
"01.2.2":"شروط السلم · رأس المال والأجل · المسلم فيه · عقد الاستصناع وحكمه",
"01.2.3":"أجرة المثل · إجارة الأعيان · إجارة الأشخاص · الفسخ والأعذار · ضمان الأجير",
"01.2.4":"شركة الأملاك · شركة العقود · المفاوضة · العنان · الوجوه والأبدان",
"01.2.5":"رأس المال · شرط الربح · تصرف المضارب · الفساد وأجر المثل · تحمّل الخسارة",
"01.2.6":"شروط الصحة · قسمة الخارج · مدة العقد · النفقة على الأرض · الفسخ بالعذر",
"01.2.7":"ما تجوز به الوكالة · وكالة الخصومة · وكالة البيع والشراء · العزل والانعزال",
"01.2.8":"كفالة النفس · كفالة المال · شروط الحوالة · براءة المحيل · الرجوع بالضمان",
"01.2.9":"القبض وأثره · ضمان الرهن · نفقة المرهون · الانتفاع به · فكاك الرهن",
"01.2.10":"حكم القرض · المثلي والقيمي · التأجيل · الإبراء · المطل والحبس",
"01.2.11":"الأمانة والضمان · التعدّي · العارية المؤقتة · نفقة العارية · الردّ",
"01.2.12":"القبض · هبة المشاع · الرجوع في الهبة · العمرى والرقبى · الصدقة",
"01.2.13":"اللزوم · شروط الواقف · الناظر والغلّة · الاستبدال · وقف المشاع",
"01.2.14":"ضمان المثل والقيمة · تغيّر المغصوب · الغلّة والزوائد · المباشرة والتسبّب",
"01.2.15":"أسباب الشفعة · الطلب والإشهاد · قسمة الجمع والتفريق · القرعة · مؤنة القسمة",
"01.2.16":"التعريف بها · حكم الالتقاط · الضالّة · إحياء الأرض · الإقطاع والتحجير",
"01.2.17":"قسمة الماء · الشفة والسقي · كري الأنهار · الطريق والفناء · التعلّي والجدار المشترك",
"01.2.18":"أسباب الحجر · الصغر والسفه · العبد المأذون · الإكراه الملجئ · أثره في التصرفات",
"01.2.19":"نسب اللقيط ونفقته · ردّ الآبق والجعل · مدة انتظار المفقود · ميراثه",
"01.3.0":"التجهيز والتكفين · قضاء الديون · تنفيذ الوصية · ترتيب الحقوق الأربعة",
"01.3.1":"حدّ الثلث · الوصية للوارث · الرجوع عنها · الوصيّ وتصرفه",
"01.3.2":"أصحاب الفروض · العصبات · الحجب · العول والردّ · ذوو الأرحام · المناسخة · ميراث الحمل والمفقود",
"01.4.0":"الزنا والإحصان · الشرب · القذف · الشبهات الدارئة · الإقرار والرجوع عنه",
"01.4.1":"النصاب والحرز · شروط القطع · السرقة الصغرى والكبرى · حدّ الحرابة · الضمان مع القطع",
"01.4.2":"العمد وشبه العمد · الخطأ · شروط القصاص · العفو والصلح · التداخل",
"01.4.3":"دية النفس · الأطراف والجروح · الشِّجاج · العاقلة · القسامة",
"01.4.4":"مقداره · اختلافه بالأشخاص · التعزير بالمال · تعزير السلطان",
"01.5.0":"شروط القاضي · التقليد والعزل · مجلس القضاء · القضاء بالعلم · كتاب القاضي",
"01.5.1":"العدالة · نصاب الشهادة · شهادة النساء · الجرح والتعديل · الرجوع عن الشهادة",
"01.5.2":"تحرير الدعوى · البينة على المدّعي · اليمين على المنكر · النكول · التحالف",
"01.5.3":"صيغته · الاستثناء فيه · الإقرار بالمجهول · إقرار المريض · الرجوع عنه",
"01.5.4":"الصلح عن إقرار · عن إنكار · عن دم · حطيطة الدين · صلح الورثة",
"01.5.5":"دعوة الكفار · الأمان والمستأمن · الغنائم والخمس · الأسرى · دار الحرب والإسلام",
"01.5.6":"مقدار الجزية · شروط العقد · أحكام الذمّي · نقض الذمة · المعاهدون",
"01.5.7":"الاستتابة · أحكام المرتد وماله · المرتدّة · قتال البغاة · أموالهم",
"01.6.0":"المنعقدة واللغو والغموس · البرّ والحنث · الاستثناء · العرف في الأيمان",
"01.6.1":"نذر اللجاج · النذر المطلق · نذر المعصية · الوفاء والكفارة",
"01.6.2":"كفارة اليمين · كفارة الظهار · كفارة القتل · كفارة الفطر · الترتيب والتخيير",
"01.6.3":"صيغ العتق · عتق البعض · التدبير · أمّ الولد · العتق في الكفارات",
"01.6.4":"عقد الكتابة · بدل الكتابة · العجز والفسخ · كسب المكاتب · عتقه بالأداء",
"01.6.5":"ولاء العَتاقة · ولاء الموالاة · انتقال الولاء · الإرث به",
"01.7.0":"التسمية · أهلية الذابح · محلّ الذكاة · ذبيحة الكتابي · حال الاضطرار",
"01.7.1":"الكلب والبازي · السهم والآلة · إرسال الصيد · صيد الحرم والمحرم · ما يؤكل منه",
"01.7.2":"الحيوان المأكول · الميتة والدم · الأشربة المحرَّمة · التداوي بالمحرَّم · آداب الأكل",
"01.7.3":"الحرير والذهب · التشبّه · ستر العورة · النظر والمسّ · الخضاب والتصوير",
"01.7.4":"الاستنجاء · آداب المسجد · البيع وقت النداء · اللهو والملاهي · الاستئذان",
/* ---- 07 القواعد ---- */
"07.0.0":"محلّ النية · وقتها · العبادات المقصودة لذاتها",
"07.0.1":"المعاني لا الألفاظ · الهزل في العقود · صور المخادعة",
"07.0.2":"قتل الموروث · طلاق الفارّ · حرمان المستعجل",
"07.0.3":"نية الحالف · عرف اللفظ · يمين القاضي والمظلوم",
"07.1.0":"استصحاب الحال · بقاء الدين حتى يثبت السداد · حكم المفقود",
"07.1.1":"البينة على المدّعي · القول قول المنكر · تقدير الأقلّ عند الاختلاف",
"07.1.2":"الأعيان المنتفع بها · ما سكت عنه الشارع · مقابله الأصل في الأبضاع التحريم",
"07.1.3":"تقديم النصّ على الظاهر · الشرط الصريح · إلغاء العرف عند التصريح",
"07.1.4":"إضافة العيب · وقت الجنون · وقوع النجاسة في البئر",
"07.2.0":"أكل الميتة · التلفظ بالكفر إكراهًا · التداوي بالمحرَّم",
"07.2.1":"قدر سدّ الرمق · كشف العورة للعلاج · أخذ قدر الحاجة فقط",
"07.2.2":"عامة كانت أو خاصة · عقد الاستصناع · السلم والإجارة",
"07.2.3":"التيمم عند وجود الماء · القعود في الصلاة · الفطر في السفر",
"07.2.4":"عموم البلوى · تخفيف المسافر والمريض · اتساع باب الرخص",
"07.3.0":"رفع الضرر بعد وقوعه · الخيارات · الردّ بالعيب",
"07.3.1":"منع إتلاف مالٍ لإنقاذ مثله · مسألة المخمصة",
"07.3.2":"الحجر على السفيه · هدم الجدار المائل · ارتكاب أخفّ الضررين",
"07.3.3":"التسعير · نزع الملكية للمصلحة · الحجر على المفتي الماجن",
"07.3.4":"تقديم الدرء على جلب المصلحة · ترك المستحبّ لدفع مفسدة",
"07.4.0":"العرف العملي · اعتبار المعاملات الجارية بين الناس",
"07.4.1":"الشرط العرفي في العقود · أجرة المثل · تسليم المبيع",
"07.4.2":"تقدير النفقة · تحديد المهر · مقادير الأجرة",
"07.4.3":"الغالب الشائع لا النادر · العرف المقارن للعقد",
"07.4.4":"تغيّر الفتوى لا النصّ · مسائل ابن عابدين · الضوابط المصلحية",
"07.5.0":"عموم القاعدة · خصوص الضابط بالباب · أمثلة كلٍّ منهما",
"07.5.1":"ضوابط الطهارة · ضوابط البيوع · اختلافها بين المذاهب",
"07.5.2":"الفرق بين الشرط والسبب · بين الفاسد والباطل · كتب الفروق",
"07.5.3":"النظائر المتشابهة · الألغاز الفقهية · كتابا ابن نجيم والسيوطي",
"07.5.4":"خرق القاعدة · المسائل المستثناة · تعليل الاستثناء",
/* ---- 08 التزكية ---- */
"08.0.0":"أسرار الطهارة والصلاة · أسرار الزكاة والصوم · أسرار الحج · الحضور والخشوع",
"08.0.1":"الآداب الظاهرة · الآداب الباطنة · التدبّر والتأثّر · الترقّي في الفهم",
"08.0.2":"شروط الإجابة · أوقات الدعاء · الأدعية المأثورة · الاستغفار",
"08.0.3":"الحلال والشبهات · آداب التجارة · القصد في الإنفاق · الورع في المطعم",
"08.1.0":"حقيقة الكبر · أسبابه · الفرق بينه وبين العجب · دواؤه بالتواضع",
"08.1.1":"حقيقته ودرجاته · الفرق عن الغبطة · أسبابه · دواؤه",
"08.1.2":"الخفيّ والجليّ · الشرك الأصغر · الرياء بعد العمل · دواؤه بإخفاء العمل",
"08.1.3":"مبادئ الغضب · كظم الغيظ · الحقد والضغينة · العفو والحلم",
"08.1.4":"ذمّ الدنيا · حبّ الجاه · البخل والشحّ · أثره في القلب",
"08.1.5":"الغيبة والنميمة · الكذب · الجدال والمراء · فضول الكلام · السخرية",
"08.1.6":"الجوع وفوائده · كسر الشهوة · غضّ البصر · الصيام علاجًا",
"08.2.0":"شروطها · التوبة النصوح · الإصرار والعَود · حقوق العباد",
"08.2.1":"أقسام الصبر الثلاثة · مقام الشكر · الصبر على الطاعة والمعصية والبلاء",
"08.2.2":"التوازن بينهما · خوف العارفين · اليأس والقنوط · حسن الظنّ بالله",
"08.2.3":"درجات الزهد · الفقر والغنى · القناعة · التقلّل من الدنيا",
"08.2.4":"حقيقته · مع الأخذ بالأسباب · درجاته · التفويض",
"08.2.5":"تصفية النية · الصدق في الأقوال والأحوال · شوائب النية",
"08.2.6":"علامات المحبة · الأنس والشوق · الرضا بالقضاء · أثرها في العمل",
"08.2.7":"قصر الأمل · زيارة القبور · الاعتبار بالموتى · أحوال المحتضر",
"08.3.0":"ترتيب المقامات · شرط الثبات · التدرّج فيها · السير والترقّي",
"08.3.1":"القبض والبسط · الهيبة والأنس · الفناء والبقاء · عدم دوامها",
"08.3.2":"الاكتساب والوهب · الثبات والزوال · خطأ الخلط بينهما",
"08.3.3":"مجاهدة النفس الأمّارة · تدريج الرياضة · مخالفة الهوى · علاج الخُلُق بضدّه",
"08.3.4":"حجيته · ضابطه بالشرع · الخواطر والوساوس · الفراسة",
"08.4.0":"الجهري والخفيّ · آداب الذاكر · ثمراته",
"08.4.1":"ترتيب الأوراد · أوراد الليل والنهار · المداومة وإن قلّت",
"08.4.2":"المشارطة · المراقبة · المحاسبة · المعاتبة",
"08.4.3":"ميادين التفكّر · التفكّر في آلاء الله · التفكّر في النفس · ثمرته باليقين",
"08.5.0":"شروط الشيخ · أدب المريد · البيعة والتلقين · شيخ التربية وشيخ التعليم",
"08.5.1":"حقوق الأخوّة · الإيثار · حفظ الغيب · أدب المعاشرة",
"08.5.2":"فوائد العزلة · آفاتها · الخلطة النافعة · الأربعينية",
"08.5.3":"شروطه · مراتب التغيير · الحسبة · أدب الآمر",
"08.5.4":"آداب السفر · سفر الطلب والحج · السماع وحكمه · الوجد"
}
